/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReceptenRouteImport } from './routes/_authenticated/recepten'
import { Route as AuthenticatedNieuwRouteImport } from './routes/_authenticated/nieuw'
import { Route as AuthenticatedInstellingenRouteImport } from './routes/_authenticated/instellingen'
import { Route as AuthenticatedGenererenRouteImport } from './routes/_authenticated/genereren'
import { Route as AuthenticatedReceptIdRouteImport } from './routes/_authenticated/recept.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReceptenRoute = AuthenticatedReceptenRouteImport.update({
  id: '/_authenticated/recepten',
  path: '/recepten',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNieuwRoute = AuthenticatedNieuwRouteImport.update({
  id: '/_authenticated/nieuw',
  path: '/nieuw',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInstellingenRoute =
  AuthenticatedInstellingenRouteImport.update({
    id: '/_authenticated/instellingen',
    path: '/instellingen',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGenererenRoute = AuthenticatedGenererenRouteImport.update({
  id: '/_authenticated/genereren',
  path: '/genereren',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReceptIdRoute = AuthenticatedReceptIdRouteImport.update({
  id: '/_authenticated/recept/$id',
  path: '/recept/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/genereren': typeof AuthenticatedGenererenRoute
  '/instellingen': typeof AuthenticatedInstellingenRoute
  '/nieuw': typeof AuthenticatedNieuwRoute
  '/recepten': typeof AuthenticatedReceptenRoute
  '/recept/$id': typeof AuthenticatedReceptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/genereren': typeof AuthenticatedGenererenRoute
  '/instellingen': typeof AuthenticatedInstellingenRoute
  '/nieuw': typeof AuthenticatedNieuwRoute
  '/recepten': typeof AuthenticatedReceptenRoute
  '/recept/$id': typeof AuthenticatedReceptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/genereren': typeof AuthenticatedGenererenRoute
  '/_authenticated/instellingen': typeof AuthenticatedInstellingenRoute
  '/_authenticated/nieuw': typeof AuthenticatedNieuwRoute
  '/_authenticated/recepten': typeof AuthenticatedReceptenRoute
  '/_authenticated/recept/$id': typeof AuthenticatedReceptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/genereren'
    | '/instellingen'
    | '/nieuw'
    | '/recepten'
    | '/recept/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/genereren'
    | '/instellingen'
    | '/nieuw'
    | '/recepten'
    | '/recept/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/genereren'
    | '/_authenticated/instellingen'
    | '/_authenticated/nieuw'
    | '/_authenticated/recepten'
    | '/_authenticated/recept/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedGenererenRoute: typeof AuthenticatedGenererenRoute
  AuthenticatedInstellingenRoute: typeof AuthenticatedInstellingenRoute
  AuthenticatedNieuwRoute: typeof AuthenticatedNieuwRoute
  AuthenticatedReceptenRoute: typeof AuthenticatedReceptenRoute
  AuthenticatedReceptIdRoute: typeof AuthenticatedReceptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recepten': {
      id: '/_authenticated/recepten'
      path: '/recepten'
      fullPath: '/recepten'
      preLoaderRoute: typeof AuthenticatedReceptenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nieuw': {
      id: '/_authenticated/nieuw'
      path: '/nieuw'
      fullPath: '/nieuw'
      preLoaderRoute: typeof AuthenticatedNieuwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/instellingen': {
      id: '/_authenticated/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof AuthenticatedInstellingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/genereren': {
      id: '/_authenticated/genereren'
      path: '/genereren'
      fullPath: '/genereren'
      preLoaderRoute: typeof AuthenticatedGenererenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recept/$id': {
      id: '/_authenticated/recept/$id'
      path: '/recept/$id'
      fullPath: '/recept/$id'
      preLoaderRoute: typeof AuthenticatedReceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedGenererenRoute: AuthenticatedGenererenRoute,
  AuthenticatedInstellingenRoute: AuthenticatedInstellingenRoute,
  AuthenticatedNieuwRoute: AuthenticatedNieuwRoute,
  AuthenticatedReceptenRoute: AuthenticatedReceptenRoute,
  AuthenticatedReceptIdRoute: AuthenticatedReceptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
