/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedReceptenRouteImport } from './routes/_authenticated/recepten'
import { Route as AuthenticatedNieuwRouteImport } from './routes/_authenticated/nieuw'
import { Route as AuthenticatedInstellingenRouteImport } from './routes/_authenticated/instellingen'
import { Route as AuthenticatedGenererenRouteImport } from './routes/_authenticated/genereren'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicAcWebhookRouteImport } from './routes/api/public/ac-webhook'
import { Route as AuthenticatedReceptIdRouteImport } from './routes/_authenticated/recept.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceptenRoute = AuthenticatedReceptenRouteImport.update({
  id: '/recepten',
  path: '/recepten',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNieuwRoute = AuthenticatedNieuwRouteImport.update({
  id: '/nieuw',
  path: '/nieuw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstellingenRoute =
  AuthenticatedInstellingenRouteImport.update({
    id: '/instellingen',
    path: '/instellingen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenererenRoute = AuthenticatedGenererenRouteImport.update({
  id: '/genereren',
  path: '/genereren',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAcWebhookRoute = ApiPublicAcWebhookRouteImport.update({
  id: '/api/public/ac-webhook',
  path: '/api/public/ac-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReceptIdRoute = AuthenticatedReceptIdRouteImport.update({
  id: '/recept/$id',
  path: '/recept/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/genereren': typeof AuthenticatedGenererenRoute
  '/instellingen': typeof AuthenticatedInstellingenRoute
  '/nieuw': typeof AuthenticatedNieuwRoute
  '/recepten': typeof AuthenticatedReceptenRoute
  '/recept/$id': typeof AuthenticatedReceptIdRoute
  '/api/public/ac-webhook': typeof ApiPublicAcWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/genereren': typeof AuthenticatedGenererenRoute
  '/instellingen': typeof AuthenticatedInstellingenRoute
  '/nieuw': typeof AuthenticatedNieuwRoute
  '/recepten': typeof AuthenticatedReceptenRoute
  '/': typeof AuthenticatedIndexRoute
  '/recept/$id': typeof AuthenticatedReceptIdRoute
  '/api/public/ac-webhook': typeof ApiPublicAcWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/genereren': typeof AuthenticatedGenererenRoute
  '/_authenticated/instellingen': typeof AuthenticatedInstellingenRoute
  '/_authenticated/nieuw': typeof AuthenticatedNieuwRoute
  '/_authenticated/recepten': typeof AuthenticatedReceptenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/recept/$id': typeof AuthenticatedReceptIdRoute
  '/api/public/ac-webhook': typeof ApiPublicAcWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/genereren'
    | '/instellingen'
    | '/nieuw'
    | '/recepten'
    | '/recept/$id'
    | '/api/public/ac-webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/genereren'
    | '/instellingen'
    | '/nieuw'
    | '/recepten'
    | '/'
    | '/recept/$id'
    | '/api/public/ac-webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/genereren'
    | '/_authenticated/instellingen'
    | '/_authenticated/nieuw'
    | '/_authenticated/recepten'
    | '/_authenticated/'
    | '/_authenticated/recept/$id'
    | '/api/public/ac-webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAcWebhookRoute: typeof ApiPublicAcWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recepten': {
      id: '/_authenticated/recepten'
      path: '/recepten'
      fullPath: '/recepten'
      preLoaderRoute: typeof AuthenticatedReceptenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nieuw': {
      id: '/_authenticated/nieuw'
      path: '/nieuw'
      fullPath: '/nieuw'
      preLoaderRoute: typeof AuthenticatedNieuwRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instellingen': {
      id: '/_authenticated/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof AuthenticatedInstellingenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/genereren': {
      id: '/_authenticated/genereren'
      path: '/genereren'
      fullPath: '/genereren'
      preLoaderRoute: typeof AuthenticatedGenererenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ac-webhook': {
      id: '/api/public/ac-webhook'
      path: '/api/public/ac-webhook'
      fullPath: '/api/public/ac-webhook'
      preLoaderRoute: typeof ApiPublicAcWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recept/$id': {
      id: '/_authenticated/recept/$id'
      path: '/recept/$id'
      fullPath: '/recept/$id'
      preLoaderRoute: typeof AuthenticatedReceptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedGenererenRoute: typeof AuthenticatedGenererenRoute
  AuthenticatedInstellingenRoute: typeof AuthenticatedInstellingenRoute
  AuthenticatedNieuwRoute: typeof AuthenticatedNieuwRoute
  AuthenticatedReceptenRoute: typeof AuthenticatedReceptenRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedReceptIdRoute: typeof AuthenticatedReceptIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedGenererenRoute: AuthenticatedGenererenRoute,
  AuthenticatedInstellingenRoute: AuthenticatedInstellingenRoute,
  AuthenticatedNieuwRoute: AuthenticatedNieuwRoute,
  AuthenticatedReceptenRoute: AuthenticatedReceptenRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedReceptIdRoute: AuthenticatedReceptIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAcWebhookRoute: ApiPublicAcWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
